---
.travis.yml:
  secure: "tJxdfj1JCPSX61grU3tMGpRL5MRj38MoG0/NwlWC0N+lpchi6KV+DMdioqrPVwRtGixKlVYISS/2AeFVpZmrDtMzPKdkAOEoE2BT9LuRK7yC39ehzxOwwTNc9mfWBJhPOQsS7lGu7RJx3VfSxGCEI2TC9DvkkbJekhJmO5yAsFQ="
  docker_sets:
    - set: ubuntu1404-64
    - set: ubuntu1604-64
    - set: ubuntu1804-64
    - set: centos7-64
    - set: debian8-64
    - set: debian9-64
